# The directory where the script looks for PressBook or WordPress XML files.
source_dir: book-xml

# The target directory where all output is saved.
build_dir: build

# Try to download and reloacate all images locally to the book.
download_images: False

# Whether to import with a flat file structure or with organization
# in folders. How the content is organized depends on the book, and
# whether the file is a PressBooks or WordPress XML (seems to work)
# better for PressBooks.
flat_output: False

# Item types we don't want to import.
item_type_filter: {attachment, nav_menu_item, page, metadata, part}

# filter by any field type on the post.
# By default, we're filtering based on field "status" set to "draft"
item_field_filter: {status: draft, body: 'None'}

# Replace certain patterns in body
# Simply replace the key with its value
body_replace: {
  '  +': ''
}
